config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :comments, only: [:create, :destroy]
  resources :posts

  devise_for :users
  resources :users do
    member do
      post :edit_avatar
    end
  end
  root 'home#index'
 

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
	belongs_to :commenter, class_name: 'User'
	has_many :replies, class_name: 'Comment', as: :commentable, dependent: :destroy

	def post
		if commentable.class.to_s == "Post"
			commentable
		else
			commentable.post
		end
	end
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :picture, ImageUploader
	belongs_to :imageable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :author, class_name: 'User'
	has_many :comments, as: :commentable 
	mount_uploader :cover_image, ImageUploader
	validates_presence_of :snippet, :body, :cover_image, :title, :author_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'commenter_id', dependent: :destroy
  mount_uploader :avatar, ImageUploader

  scope :members, -> { where(is_member: true)}
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :post
	before_create :set_embedded_iframe


	private

	def set_embedded_iframe
		self.embedded_iframe = YouTubeAddy.youtube_embed_url self.url, 420, 315
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(user)
  	posts_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :require_user_ownership, :prepare_comment, only: [:destroy]
  def create
  	@comment = Comment.create(body: params[:body], commenter: current_user, commentable_id: params[:commentable_id], commentable_type: params[:commentable_type])
  	redirect_to :back
  end
  
  def destroy
    @comment.destroy
  	redirect_to :back
  end

  private

  def prepare_comment
  	@comment = Comment.find(params[:id])
  end

  def require_user_ownership
  	@comment.commenter_id == current_user.id || @comment.post.author_id == current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@members = User.members
		render layout: 'home'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :prepare_post, only: [:destroy]
	before_filter :authenticate_user!, only: [:create, :destory]
	before_filter :require_user_ownership, only: [:destroy]
	def index 
		@posts = Post.all
	end

	def show 
		@post = Post.includes(:comments).find(params[:id])
	end 


	def create
		@post = Post.new post_params
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def new
		@post = Post.new
	end

	def destory
		@post.destory
		redirect_to posts_path
	end

	private

	def prepare_post
		@post = Post.find(params[:id])
	end

	def require_user_ownership
		@post.present? && @post.author_id == current_user.id
	end

	def post_params
		post = params.require(:post).permit(:body, :title, :snippet, :cover_image)
		post[:author] = current_user
		post
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!, except: [:show]
	def show
		@user = User.find params[:id]
		unless @user.is_member
			redirect_to posts_path
		end
	end

	def edit

	end

	def edit_avatar
		current_user.avatar = params[:avatar]
		current_user.save
		redirect_to :back
	end

	def update
		current_user.name = params[:name]
		current_user.biography = params[:biography]
		current_user.save
		redirect_to :back
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_hero_image_helper(post)
		image_tag post.cover_image.url
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def user_avatar_helper(user)
		image_tag(user.avatar.url || 'avatar.jpg')
	end

	def user_name_link_helper(user)
		name = user.name || 'Anonymous'
		if user.is_member 
			link_to name, user
		else
			name
		end
	end
end

app/views/comments/_comment.html.erb
<div class='comment-content' id='comment_<%= comment.id %>'>
	<div class='avatar left'>
		<%= user_avatar_helper(comment.commenter) %>
	</div>
	<div class='comment-body'>
		<header><span><%= user_name_link_helper comment.commenter%></span>   <span><%= "#{time_ago_in_words(comment.created_at)} ago"%></span></header>
		<p>
			<%= comment.body %>
		</p>
		<footer>
			<span><%= link_to 'Reply', '#', id: "reply-link-#{comment.id}", data: {id: comment.id} %></span>
		</footer>
		<ul class='comments replies-wrapper'>
			<% comment.replies.each do |reply| %>
				<li><%= render partial: 'comments/comment', locals: {comment: reply} %></li>
			<% end %>
		</ul>
	</div>
</div>

<script>
	$(document).ready(function(){
		var replyLink = '<%= "#reply-link-#{comment.id}"%>'
		$(replyLink).on('click', function(e){
			e.preventDefault();
			var link = $(e.currentTarget);
			var id = link.data('id');
			var parent = $('#comment_'+id);
			var html = '<%=j render partial: "comments/form", locals: {commentable_type: "Comment", commentable_id: comment.id}%>'
			html = "<div class='reply-wrapper'>"+html+"</div>";
			parent.append(html);
		});
	});
</script>


app/views/comments/_form.html.erb
<div id='post-form'>
	<%= form_tag comments_path(commentable_id: commentable_id, commentable_type: commentable_type), class: 'comment_form' do %>
		<div class='post-box'>
			<div class='post-image left'>
				<%= user_avatar_helper(current_user) %>
			</div>
			<div class='post-body'>
				<div class='post-textarea-wrapper'>
					<%= text_field_tag :body, '', placeholder: 'Join the discussion... ', class: 'form-body'%>
					<div class='post-actions'>
						<%= submit_tag 'Post', class: 'right post-submit comment-submit' %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/home/_carousel.html.erb
<div class='carousel-container'>
	<div class="single-item carousel">
		<div class='slide'>
			<div>
				<h2 class="title">PSD CONCEPT</h2>
				<h3 class="title">CREATIVE PORTFOLIO</h3>
				<p class="description">WEB DESIGN . DEVELOPMENT . MARKETING</p>  
			</div>
		</div>
		<div>
			<div class='slide'>
				<div>
					<h2 class="title">PSD CONCEPT</h2>
					<h3 class="title">CREATIVE PORTFOLIO</h3>
					<p class="description">WEB DESIGN . DEVELOPMENT . MARKETING</p>  
				</div>
			</div>
		</div>
		<div>
			<div class='slide'>
				<div>
					<h2 class="title">PSD CONCEPT</h2>
					<h3 class="title">CREATIVE PORTFOLIO</h3>
					<p class="description">WEB DESIGN . DEVELOPMENT . MARKETING</p>  
				</div> 
			</div>
		</div>
		<div>
			<div class='slide'>
				<div>
					<h2 class="title">PSD CONCEPT</h2>
					<h3 class="title">CREATIVE PORTFOLIO</h3>
					<p class="description">WEB DESIGN . DEVELOPMENT . MARKETING</p>  
				</div> 
			</div>
		</div>
	</div>
	<div class='carousel-dots'>
	</div>		
</div>

app/views/home/_contact.html.erb
<section class='home-section' id='contact'>
	<div class='row'>
		<div class='row title'>
			<h2>CONTACT US</h2>
			<h3>lorem slogan contact us now</h3>
		</div>

		<div class='row form'>
			<div class='small-6 small-centered columns'>
			<%= form_tag '#' do %>
				<%= text_field_tag :name, nil, placeholder: 'Name'%>
				<%= text_field_tag :email, nil, placeholder: 'Email' %>
				<%= text_area_tag :message,nil, placeholder:'Message', rows: 12%><br />
				<div class='small-4 small-centered columns'>
					<%= submit_tag 'Submit', class: 'contact-submit button radius ' %>
				</div>
			<% end %>
		</div>
		</div>
	</div>
</section>

app/views/home/_contact_logos.html.erb
<section id='contact-logos'> 
	<div class='small-8 small-centered columns'> 
		<ul class='small-block-grid-2'>
			<li><%= image_tag 'client6.png'%></li>
			<li><%= image_tag 'client7.png'%></li>
		</ul>
	</div>
</section>

app/views/home/_services.html.erb
<section class='home-section' id='services'>
	<div class='row'>
		<div class='row title'>
			<h2>Services</h2>
			<h3>A bit of lorem text lorems</h3>
		</div>
		<div class='row'>
			<div class='small-4 columns service-description'>
				<%= image_tag 'service1.png' %>
				<h4>PIXEL PERFECT</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class='small-4 columns service-description'>
				<%= image_tag 'service2.png' %>
				<h4>PIXEL PERFECT</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class='small-4 columns service-description'>
				<%= image_tag 'service3.png' %>
				<h4>PIXEL PERFECT</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
		</div>
	</div>
</section>

app/views/home/_sticky_top.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar role="navigation">
  	<section class="top-bar-section">
  		<ul class="title-area">
  		  <li class="name">
  		    <h1><a href="#">SQUIB</a></h1>
  		  </li>
  		</ul>
  	  <ul class="right">
  	    <li ><a href="#">Home</a></li>
  	    <li ><a href="#services">Services</a></li>
  	    <li ><a href="#team">Team</a></li>
  	    <li ><a href="#contact">Contact</a></li>
  	    <li ><%= link_to 'Blog', posts_path%></li>
  	  </ul>
  </nav>
</div>

app/views/home/_team.html.erb
<section class='home-section' id='team'>
	<div class='row'>
		<div class='row title'>
			<h2>SQUIBERS</h2>
			<h3>Meet the squibers lorem ipsum</h3>
		</div>
		<div class='row'>
			<ul class="small-block-grid-3">
				<% @members.each do |member| %>
					<li><%= render partial: 'users/member_card', locals: {member: member} %></li>
				<% end %>
			</ul>
		</div>
	</div>
</section>

app/views/home/index.html.erb
<%= render 'carousel' %>
<%= render 'sticky_top' %>
<%= render 'services' %>
<%= render 'team' %>
<%= render 'contact_logos' %>
<%= render 'contact' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body >
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to 'SQUIB', root_path %></h1>
        </li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <li><%= link_to 'Latest', posts_path%></li>
          <% if current_user %>
            <% if current_user.is_member || current_user.authorized %>
              <li><%= link_to 'Compose', new_post_path %></li>
              <li><%= link_to 'Profile', current_user%></li>
            <% end %>
            <li><%= link_to 'Settings', edit_user_path(current_user)%></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>

          <% else %>
            <li><%= link_to 'Sign in', user_session_path %></li>
          <% end %>
        </ul>

      </section>
    </nav>
    <%= yield %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/posts/_card.html.erb
<div class="blog-card">
 	<div class="small-5 columns left blog-image">
 		<%= post_hero_image_helper post %>
 	</div>	
 	<div class="small-7 right blog-text">
 		<h6><%= "#{time_ago_in_words(post.created_at)} ago" %></h6>
 		<h3><%= link_to post.title, post_path(post) %></h3>
 			<%= image_tag 'line.png' %>
 		<p><%= "#{post.snippet.first(85)}..." %></p>
 		<p><%= link_to 'MORE', post_path(post) %></p>
 	</div>
    <div class="clear"> </div>
</div>

app/views/posts/index.html.erb
<section class='home-section'>
 	<div class='blog-content'>
 		<div class='blog-feed row'>
		 	<ul class='small-block-grid-2'>
		 		<% @posts.each do |post| %>
		 			<li><%= render partial: 'card', locals: {post: post} %></li>
		 		<% end %>
		 	</ul>
 		</div>
  </div>
</section>

app/views/posts/new.html.erb
<div class='row'>
<%= form_for @post, html: {multipart: true} do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title, style: 'width:100%' %>
	</p>

	<p>
		<%= form.label :body %>
		<%= form.cktext_area :body, :ckeditor => {:toolbar => 'inline'} %>

	</p>

	<p>
		<%= form.label :snippet %>
		<%= form.text_field :snippet %>
	</p>

	<p>
		<%= form.label :cover_image %>
		<%= form.file_field :cover_image%>
	</p>
	<%= form.submit %>
<% end %>
</div>

app/views/posts/show.html.erb
<section class='home-section' style='background:#f8f8f8'>
	<div class='row'>
		<h1><%= @post.title %></h1>
		<p>By <%= user_name_link_helper @post.author %></p>
		<div class='post-content'>
			<%= @post.body.html_safe %>
		</div>
		<hr />
		<h6><%= "#{time_ago_in_words(@post.created_at)} ago" %></h6>
		<br />
		<h4><%= "#{@post.comments.count} Comments"%></h4>
		<br />
		<div class='comments-content'>
			<% if current_user %>
				<%= render partial: 'comments/form', locals: {commentable_type: 'Post', commentable_id: @post.id} %>
			<% end %>
			<ul class='comments'>
				<% @post.comments.each do |comment| %>
					<li><%= render partial: 'comments/comment', locals: {comment: comment} %></li>
				<% end %>
			</ul>
		</div>
	</div>
</section>

app/views/users/_account.html.erb
<%= form_for(user, url: registration_path(user), html: { method: :put }) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(user), data: { confirm: "Are you sure?" }, method: :delete %></p>

app/views/users/_avatar.html.erb
<%= form_tag edit_avatar_user_path(user), multipart: true do %>
	<div class='avatar-edit left'>
		<%= user_avatar_helper(user) %>
	</div>
	<div>
		<%= file_field_tag :avatar %>
		<%= submit_tag 'Save', class: 'button radius' %>
	</div>
<% end %>

app/views/users/_edit.html.erb
<%= form_tag user_path(user), method: :put do %>
	<p>
		<%= label_tag :name %>
		<%= text_field_tag :name, user.name %>
	</p>

	<p>
		<%= label_tag :biography %>
		<%= text_field_tag :biography, user.biography %>
	</p>

	<p>
		<%= submit_tag 'Save', class: 'button radius'%>
	</p>
<% end %>

app/views/users/_member_card.html.erb
<div class='squibers-grid-card'>
	<%= image_tag member.avatar_url %>
	<h4><%= link_to member.name, user_path(member)%></h4>
	<h5>Developer</h5>
	<ul class="top-social-icons">
		<li><%= link_to '', '#', class: 'twitter', data: {tooltip: "twitter"}%></li>
		<li><%= link_to '', '#', class: 'facebook', data: {tooltip: "facebook"}%></li>
		<div class="clear"> </div>
	</ul>
</div>

app/views/users/edit.html.erb
<section class='home-section'>
<div class='row'>
	<ul class="side-nav small-3 columns">
	  <li><a class='edit-sub-user' href="#">Info</a></li>
	  <li><a class='edit-sub-avatar' href="#">Avatar</a></li>
	  <li><a class='edit-sub-account' href="#">Account</a></li>
	</ul>

	<div class='edit-user-content small-9 columns'>
		<%= render partial: 'edit', locals: {user: current_user} %>
	</div>
</div>
</section>

<script>
	$(document).ready(function(){
		$('.edit-sub-user').on('click', function(e){
			e.preventDefault();
			var html = "<%=j render partial: 'edit', locals: {user: current_user}%>";
			$('.edit-user-content').html(html);
		});

		$('.edit-sub-avatar').on('click', function(e){
			e.preventDefault();
			var html = "<%=j render partial: 'avatar', locals: {user: current_user}%>";
			$('.edit-user-content').html(html);
		});

		$('.edit-sub-account').on('click', function(e){
			e.preventDefault();
			var html = "<%=j render partial: 'account', locals: {user: current_user}%>";
			$('.edit-user-content').html(html);
		});
	});
</script>

app/views/users/show.html.erb
<section class='home-section'>
	<div class='row'>
		<div class='small-4 columns'>
			<%= render partial: 'member_card', locals: {member: @user} %>
			<hr />
			<h6 style="font-size:13px">About</h6>
			<p><%= @user.biography %></p>
		</div>
		<div class='small-8 columns'>
	  	<% @user.posts.each do |post|%>
	  		<%= render partial: 'posts/card', locals: {post: post} %>
	  	<% end %>
		</div>
	</div>
</section>